/** 
* _DataMemory is a Java class represention of one of the components
* of the Reference Architecture of TOP_LEVEL.
* <p>
* It extends from the class Component like all other elements of TOP_LEVEL because
* this model follows the Composite design patter and SCA (Service Component Architecture)
* <p>
* It also implements the following services:
* <ul>
* <li>_i_DMem</li>
* </ul>
* <p>
* In addendum, this class also encapsulates all the configurable properties of the 
* component it represent, as well as all the accessor methods to change its values
*
* <b>NOTE:</b> Code autmatically generated by Elaboration Language
*
* @author ESRG (Embedded Systems Research Group) class of 2015/2016
* @version 1.0 
* @since 02/05/2016
*/

package EL.Components;

import java.util.ArrayList;
import java.util.Arrays;
import EL.ElaborationError;

public class _DataMemory extends Component implements _i_DMem
{
	//-------------------------- NO SUBCOMPONENTS -------------------------//
	
	
	//----------------------------- REFERENCES ----------------------------//
	protected _i_MemSizes _r_MemSizes;
	
	//--------------------------- NO PROPERTIES ---------------------------//


	public _DataMemory()
	{
		//There are no subcomponents to be initialized.
		
		
		//There are bindings to be done.
	}
	//---------------------------------------------------------------------//
	//--------------------- REFERENCES ACCESSOR METHODS -------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for _r_MemSizes which type is _i_MemSizes
	*
	* @return _r_MemSizes (Reference in _DataMemory)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_MemSizes get_r_MemSizes()
	{
		return this._r_MemSizes;
	}
	/**
	* Setter method for _r_MemSizes which type is _i_MemSizes
	*
	* @param _arg (Component to set r_MemSizes in _DataMemory that implements _i_MemSizes)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_r_MemSizes(_i_MemSizes _arg)
	{
		this._r_MemSizes = _arg;
	}			
	//---------------------------------------------------------------------//
	//----------------- END OF REFERENCES ACCESSOR METHODS ----------------//	
	//---------------------------------------------------------------------//	
	
	//---------------------------------------------------------------------//
	//--------------------- SERVICES ACCESSOR METHODS ---------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for the component that implements _i_DMem
	*
	* @return this (Component _DataMemory)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_DMem()
	{
		return this;
	}
	
	//---------------------------------------------------------------------//
	//------------------ END OF SERVICES ACCESSOR METHODS -----------------//
	//---------------------------------------------------------------------//
}	
