/** 
* _DBTEngine is a Java class represention of one of the components
* of the Reference Architecture of TOP_LEVEL.
* <p>
* It extends from the class Component like all other elements of TOP_LEVEL because
* this model follows the Composite design patter and SCA (Service Component Architecture)
* <p>
* This class contains objects(subcomponents) of the following types:
* <ul>
* <li>_Translate</li>	
* <li>_Execute</li>	
* </ul>
* <p>
* It also implements the following services:
* <ul>
* <li>_i_RunDBT</li>,
* <li>_i_CurrBBExec</li>,
* <li>_i_Init</li>
* </ul>
* <p>
* In addendum, this class also encapsulates all the configurable properties of the 
* component it represent, as well as all the accessor methods to change its values
*
* <b>NOTE:</b> Code autmatically generated by Elaboration Language
*
* @author ESRG (Embedded Systems Research Group) class of 2015/2016
* @version 1.0 
* @since 02/05/2016
*/

package EL.Components;

import java.util.ArrayList;
import java.util.Arrays;
import EL.ElaborationError;

public class _DBTEngine extends Component implements _i_RunDBT, _i_CurrBBExec, _i_Init
{
	//--------------------------- SUBCOMPONENTS ---------------------------//
	protected _Translate _translate;
	protected _Execute _execute;
	
	//----------------------------- REFERENCES ----------------------------//
	protected _i_Translate _r_Translate;
	
	//--------------------------- NO PROPERTIES ---------------------------//


	public _DBTEngine()
	{
		//Initialization of subcomponents.
		_translate = new _Translate();
		_execute = new _Execute();
		
		//Binding references to services.
		this.set_r_Translate((_i_Translate)_translate.get_i_Translate());
		_execute.set_r_CurrBBExec((_i_CurrBBExec)this.get_i_CurrBBExec());
	}
	//---------------------------------------------------------------------//
	//------------------- SUBCOMPONENTS ACCESSOR METHODS ------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for the subcomponent _Translate of _DBTEngine
	*
	* @return _Translate
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _Translate get_translate()
	{
		return this._translate;
	}
	/**
	* Getter method for the subcomponent _Execute of _DBTEngine
	*
	* @return _Execute
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _Execute get_execute()
	{
		return this._execute;
	}
	//---------------------------------------------------------------------//
	//--------------- END OF SUBCOMPONENTS ACCESSOR METHODS ---------------//
	//---------------------------------------------------------------------//
	
	//---------------------------------------------------------------------//
	//--------------------- REFERENCES ACCESSOR METHODS -------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for _r_Translate which type is _i_Translate
	*
	* @return _r_Translate (Reference in _DBTEngine)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_Translate get_r_Translate()
	{
		return this._r_Translate;
	}
	/**
	* Setter method for _r_Translate which type is _i_Translate
	*
	* @param _arg (Component to set r_Translate in _DBTEngine that implements _i_Translate)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_r_Translate(_i_Translate _arg)
	{
		this._r_Translate = _arg;
	}			
	/**
	* Getter method for _pr_DMem which type is _i_DMem
	* <p>
	* This reference is promoted from _execute
	*
	* @return _r_DMem (Reference in _execute)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_DMem get_pr_DMem()
	{
		return _execute.get_r_DMem();
	}
	/**
	* Setter method for _pr_DMem which type is _i_DMem
	* <p>
	* This reference is promoted from _execute
	*
	* @param _arg (Component to set _r_DMem in _execute that implements _i_DMem)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_pr_DMem(_i_DMem _arg)
	{
		_execute.set_r_DMem(_arg);
	}			
	/**
	* Getter method for _pr_Decode which type is _i_Decode
	* <p>
	* This reference is promoted from _translate
	*
	* @return _r_Decode (Reference in _translate)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_Decode get_pr_Decode()
	{
		return _translate.get_r_Decode();
	}
	/**
	* Setter method for _pr_Decode which type is _i_Decode
	* <p>
	* This reference is promoted from _translate
	*
	* @param _arg (Component to set _r_Decode in _translate that implements _i_Decode)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_pr_Decode(_i_Decode _arg)
	{
		_translate.set_r_Decode(_arg);
	}			
	/**
	* Getter method for _pr_TransTCache which type is _i_TCache
	* <p>
	* This reference is promoted from _translate
	*
	* @return _r_TCache (Reference in _translate)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_TCache get_pr_TransTCache()
	{
		return _translate.get_r_TCache();
	}
	/**
	* Setter method for _pr_TransTCache which type is _i_TCache
	* <p>
	* This reference is promoted from _translate
	*
	* @param _arg (Component to set _r_TCache in _translate that implements _i_TCache)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_pr_TransTCache(_i_TCache _arg)
	{
		_translate.set_r_TCache(_arg);
	}			
	//---------------------------------------------------------------------//
	//----------------- END OF REFERENCES ACCESSOR METHODS ----------------//	
	//---------------------------------------------------------------------//	
	
	//---------------------------------------------------------------------//
	//--------------------- SERVICES ACCESSOR METHODS ---------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for the component that implements _i_RunDBT
	*
	* @return this (Component _DBTEngine)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_RunDBT()
	{
		return this;
	}
	/**
	* Getter method for the component that implements _i_CurrBBExec
	*
	* @return this (Component _DBTEngine)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_CurrBBExec()
	{
		return this;
	}
	/**
	* Getter method for the component that implements _i_Init
	*
	* @return this (Component _DBTEngine)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_Init()
	{
		return this;
	}
	
	//---------------------------------------------------------------------//
	//------------------ END OF SERVICES ACCESSOR METHODS -----------------//
	//---------------------------------------------------------------------//
}	
