/** 
* _Decoder is a Java class represention of one of the components
* of the Reference Architecture of TOP_LEVEL.
* <p>
* It extends from the class Component like all other elements of TOP_LEVEL because
* this model follows the Composite design patter and SCA (Service Component Architecture)
* <p>
* It also implements the following services:
* <ul>
* <li>_i_Decode</li>
* </ul>
* <p>
* In addendum, this class also encapsulates all the configurable properties of the 
* component it represent, as well as all the accessor methods to change its values
*
* <b>NOTE:</b> Code autmatically generated by Elaboration Language
*
* @author ESRG (Embedded Systems Research Group) class of 2015/2016
* @version 1.0 
* @since 02/05/2016
*/

package EL.Components;

import java.util.ArrayList;
import java.util.Arrays;
import EL.ElaborationError;

public class _Decoder extends Component implements _i_Decode
{
	//-------------------------- NO SUBCOMPONENTS -------------------------//
	
	
	//----------------------------- REFERENCES ----------------------------//
	protected _i_ISA _r_ISA;
	protected _i_Registers _r_Registers;
	protected _i_PCAccessors _r_PCAccessors;
	protected _i_Generate _r_Generate;
	protected _i_CCache _r_CCache;
	
	//--------------------------- NO PROPERTIES ---------------------------//


	public _Decoder()
	{
		//There are no subcomponents to be initialized.
		
		
		//There are bindings to be done.
	}
	//---------------------------------------------------------------------//
	//--------------------- REFERENCES ACCESSOR METHODS -------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for _r_ISA which type is _i_ISA
	*
	* @return _r_ISA (Reference in _Decoder)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_ISA get_r_ISA()
	{
		return this._r_ISA;
	}
	/**
	* Setter method for _r_ISA which type is _i_ISA
	*
	* @param _arg (Component to set r_ISA in _Decoder that implements _i_ISA)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_r_ISA(_i_ISA _arg)
	{
		this._r_ISA = _arg;
	}			
	/**
	* Getter method for _r_Registers which type is _i_Registers
	*
	* @return _r_Registers (Reference in _Decoder)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_Registers get_r_Registers()
	{
		return this._r_Registers;
	}
	/**
	* Setter method for _r_Registers which type is _i_Registers
	*
	* @param _arg (Component to set r_Registers in _Decoder that implements _i_Registers)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_r_Registers(_i_Registers _arg)
	{
		this._r_Registers = _arg;
	}			
	/**
	* Getter method for _r_PCAccessors which type is _i_PCAccessors
	*
	* @return _r_PCAccessors (Reference in _Decoder)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_PCAccessors get_r_PCAccessors()
	{
		return this._r_PCAccessors;
	}
	/**
	* Setter method for _r_PCAccessors which type is _i_PCAccessors
	*
	* @param _arg (Component to set r_PCAccessors in _Decoder that implements _i_PCAccessors)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_r_PCAccessors(_i_PCAccessors _arg)
	{
		this._r_PCAccessors = _arg;
	}			
	/**
	* Getter method for _r_Generate which type is _i_Generate
	*
	* @return _r_Generate (Reference in _Decoder)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_Generate get_r_Generate()
	{
		return this._r_Generate;
	}
	/**
	* Setter method for _r_Generate which type is _i_Generate
	*
	* @param _arg (Component to set r_Generate in _Decoder that implements _i_Generate)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_r_Generate(_i_Generate _arg)
	{
		this._r_Generate = _arg;
	}			
	/**
	* Getter method for _r_CCache which type is _i_CCache
	*
	* @return _r_CCache (Reference in _Decoder)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_CCache get_r_CCache()
	{
		return this._r_CCache;
	}
	/**
	* Setter method for _r_CCache which type is _i_CCache
	*
	* @param _arg (Component to set r_CCache in _Decoder that implements _i_CCache)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_r_CCache(_i_CCache _arg)
	{
		this._r_CCache = _arg;
	}			
	//---------------------------------------------------------------------//
	//----------------- END OF REFERENCES ACCESSOR METHODS ----------------//	
	//---------------------------------------------------------------------//	
	
	//---------------------------------------------------------------------//
	//--------------------- SERVICES ACCESSOR METHODS ---------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for the component that implements _i_Decode
	*
	* @return this (Component _Decoder)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_Decode()
	{
		return this;
	}
	
	//---------------------------------------------------------------------//
	//------------------ END OF SERVICES ACCESSOR METHODS -----------------//
	//---------------------------------------------------------------------//
}	
