/** 
* _SourceCluster is a Java class represention of one of the components
* of the Reference Architecture of TOP_LEVEL.
* <p>
* It extends from the class Component like all other elements of TOP_LEVEL because
* this model follows the Composite design patter and SCA (Service Component Architecture)
* <p>
* This class contains objects(subcomponents) of the following types:
* <ul>
* <li>_Decoder</li>	
* <li>_Architecture</li>	
* <li>_SourceEnv</li>	
* </ul>
* <p>
* In addendum, this class also encapsulates all the configurable properties of the 
* component it represent, as well as all the accessor methods to change its values
*
* <b>NOTE:</b> Code autmatically generated by Elaboration Language
*
* @author ESRG (Embedded Systems Research Group) class of 2015/2016
* @version 1.0 
* @since 02/05/2016
*/

package EL.Components;

import java.util.ArrayList;
import java.util.Arrays;
import EL.ElaborationError;

public class _SourceCluster extends Component 
{
	//--------------------------- SUBCOMPONENTS ---------------------------//
	protected _Decoder _decoder;
	protected _Architecture _srcArch;
	protected _SourceEnv _srcEnv;
	
	//--------------------------- NO REFERENCES ---------------------------//

	
	//--------------------------- NO PROPERTIES ---------------------------//


	public _SourceCluster()
	{
		//Initialization of subcomponents.
		_decoder = new _Decoder();
		_srcArch = new _Architecture();
		_srcEnv = new _SourceEnv();
		
		//Binding references to services.
		_decoder.set_r_ISA((_i_ISA)_srcArch.get_i_ISA());
		_srcEnv.set_pr_MemSizes((_i_MemSizes)_srcArch.get_i_MemSizes());
		_decoder.set_r_Registers((_i_Registers)_srcArch.get_i_Registers());
		_decoder.set_r_PCAccessors((_i_PCAccessors)_srcEnv.get_i_PCAccessors());
	}
	//---------------------------------------------------------------------//
	//------------------- SUBCOMPONENTS ACCESSOR METHODS ------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for the subcomponent _Decoder of _SourceCluster
	*
	* @return _Decoder
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _Decoder get_decoder()
	{
		return this._decoder;
	}
	/**
	* Getter method for the subcomponent _Architecture of _SourceCluster
	*
	* @return _Architecture
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _Architecture get_srcArch()
	{
		return this._srcArch;
	}
	/**
	* Getter method for the subcomponent _SourceEnv of _SourceCluster
	*
	* @return _SourceEnv
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _SourceEnv get_srcEnv()
	{
		return this._srcEnv;
	}
	//---------------------------------------------------------------------//
	//--------------- END OF SUBCOMPONENTS ACCESSOR METHODS ---------------//
	//---------------------------------------------------------------------//
	
	//---------------------------------------------------------------------//
	//--------------------- REFERENCES ACCESSOR METHODS -------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for _pr_Generate which type is _i_Generate
	* <p>
	* This reference is promoted from _decoder
	*
	* @return _r_Generate (Reference in _decoder)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_Generate get_pr_Generate()
	{
		return _decoder.get_r_Generate();
	}
	/**
	* Setter method for _pr_Generate which type is _i_Generate
	* <p>
	* This reference is promoted from _decoder
	*
	* @param _arg (Component to set _r_Generate in _decoder that implements _i_Generate)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_pr_Generate(_i_Generate _arg)
	{
		_decoder.set_r_Generate(_arg);
	}			
	/**
	* Getter method for _pr_CCache which type is _i_CCache
	* <p>
	* This reference is promoted from _decoder
	*
	* @return _r_CCache (Reference in _decoder)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_CCache get_pr_CCache()
	{
		return _decoder.get_r_CCache();
	}
	/**
	* Setter method for _pr_CCache which type is _i_CCache
	* <p>
	* This reference is promoted from _decoder
	*
	* @param _arg (Component to set _r_CCache in _decoder that implements _i_CCache)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_pr_CCache(_i_CCache _arg)
	{
		_decoder.set_r_CCache(_arg);
	}			
	//---------------------------------------------------------------------//
	//----------------- END OF REFERENCES ACCESSOR METHODS ----------------//	
	//---------------------------------------------------------------------//	
	
	//---------------------------------------------------------------------//
	//--------------------- SERVICES ACCESSOR METHODS ---------------------//
	//---------------------------------------------------------------------//
	
	/**
	* Getter method for the component that implements _i_ISA
	* <p>
	* This service is promoted from _srcArch
	*
	* @return Component (_srcArch or any subcomponent)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_ISA()
	{
		return _srcArch.get_i_ISA();
	}
	/**
	* Getter method for the component that implements _i_Registers
	* <p>
	* This service is promoted from _srcArch
	*
	* @return Component (_srcArch or any subcomponent)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_Registers()
	{
		return _srcArch.get_i_Registers();
	}
	/**
	* Getter method for the component that implements _i_PCAccessors
	* <p>
	* This service is promoted from _srcEnv
	*
	* @return Component (_srcEnv or any subcomponent)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_PCAccessors()
	{
		return _srcEnv.get_i_PCAccessors();
	}
	/**
	* Getter method for the component that implements _i_DMem
	* <p>
	* This service is promoted from _srcEnv
	*
	* @return Component (_srcEnv or any subcomponent)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_DMem()
	{
		return _srcEnv.get_i_DMem();
	}
	/**
	* Getter method for the component that implements _i_Decode
	* <p>
	* This service is promoted from _decoder
	*
	* @return Component (_decoder or any subcomponent)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_Decode()
	{
		return _decoder.get_i_Decode();
	}
	//---------------------------------------------------------------------//
	//------------------ END OF SERVICES ACCESSOR METHODS -----------------//
	//---------------------------------------------------------------------//
}	
