# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.cache/wt [current_project]
set_property parent.project_path C:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/DBT_BD.bd
set_property used_in_implementation false [get_files -all c:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/ip/DBT_BD_processing_system7_0_0/DBT_BD_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/ip/DBT_BD_axi_bram_ctrl_0_0/DBT_BD_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/ip/DBT_BD_axi_bram_ctrl_0_1/DBT_BD_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/ip/DBT_BD_blk_mem_gen_0_0/DBT_BD_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/ip/DBT_BD_rst_processing_system7_0_100M_0/DBT_BD_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/ip/DBT_BD_rst_processing_system7_0_100M_0/DBT_BD_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/ip/DBT_BD_rst_processing_system7_0_100M_0/DBT_BD_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/ip/DBT_BD_auto_pc_0/DBT_BD_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/ip/DBT_BD_auto_pc_1/DBT_BD_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/DBT_BD_ooc.xdc]
set_property is_locked true [get_files C:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/DBT_BD.bd]

read_verilog -library xil_defaultlib C:/Users/Public/GIT-DBTGang/DBT_Gang/ZYBO/DBTZybo/DBTZybo.srcs/sources_1/bd/DBT_BD/hdl/DBT_BD_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top DBT_BD_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef DBT_BD_wrapper.dcp
catch { report_utilization -file DBT_BD_wrapper_utilization_synth.rpt -pb DBT_BD_wrapper_utilization_synth.pb }
