# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DBT_BD/DBT_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD || ORIG_REF_NAME==DBT_BD}]

# IP: bd/DBT_BD/ip/DBT_BD_processing_system7_0_0/DBT_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_processing_system7_0_0 || ORIG_REF_NAME==DBT_BD_processing_system7_0_0}]

# IP: bd/DBT_BD/ip/DBT_BD_axi_bram_ctrl_0_0/DBT_BD_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_axi_bram_ctrl_0_0 || ORIG_REF_NAME==DBT_BD_axi_bram_ctrl_0_0}]

# IP: bd/DBT_BD/ip/DBT_BD_axi_bram_ctrl_0_1/DBT_BD_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_axi_bram_ctrl_0_1 || ORIG_REF_NAME==DBT_BD_axi_bram_ctrl_0_1}]

# IP: bd/DBT_BD/ip/DBT_BD_blk_mem_gen_0_0/DBT_BD_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_blk_mem_gen_0_0 || ORIG_REF_NAME==DBT_BD_blk_mem_gen_0_0}]

# IP: bd/DBT_BD/ip/DBT_BD_axi_mem_intercon_0/DBT_BD_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_axi_mem_intercon_0 || ORIG_REF_NAME==DBT_BD_axi_mem_intercon_0}]

# IP: bd/DBT_BD/ip/DBT_BD_rst_processing_system7_0_100M_0/DBT_BD_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==DBT_BD_rst_processing_system7_0_100M_0}]

# IP: bd/DBT_BD/ip/DBT_BD_axi_mem_intercon_1_0/DBT_BD_axi_mem_intercon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_axi_mem_intercon_1_0 || ORIG_REF_NAME==DBT_BD_axi_mem_intercon_1_0}]

# IP: bd/DBT_BD/ip/DBT_BD_auto_pc_0/DBT_BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_auto_pc_0 || ORIG_REF_NAME==DBT_BD_auto_pc_0}]

# IP: bd/DBT_BD/ip/DBT_BD_auto_pc_1/DBT_BD_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_auto_pc_1 || ORIG_REF_NAME==DBT_BD_auto_pc_1}]

# XDC: bd/DBT_BD/ip/DBT_BD_processing_system7_0_0/DBT_BD_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DBT_BD_processing_system7_0_0 || ORIG_REF_NAME==DBT_BD_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/DBT_BD/ip/DBT_BD_axi_bram_ctrl_0_0/DBT_BD_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/DBT_BD/ip/DBT_BD_axi_bram_ctrl_0_1/DBT_BD_axi_bram_ctrl_0_1_ooc.xdc

# XDC: bd/DBT_BD/ip/DBT_BD_blk_mem_gen_0_0/DBT_BD_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/DBT_BD/ip/DBT_BD_rst_processing_system7_0_100M_0/DBT_BD_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==DBT_BD_rst_processing_system7_0_100M_0}]

# XDC: bd/DBT_BD/ip/DBT_BD_rst_processing_system7_0_100M_0/DBT_BD_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DBT_BD_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==DBT_BD_rst_processing_system7_0_100M_0}]

# XDC: bd/DBT_BD/ip/DBT_BD_rst_processing_system7_0_100M_0/DBT_BD_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/DBT_BD/ip/DBT_BD_auto_pc_0/DBT_BD_auto_pc_0_ooc.xdc

# XDC: bd/DBT_BD/ip/DBT_BD_auto_pc_1/DBT_BD_auto_pc_1_ooc.xdc

# XDC: bd/DBT_BD/DBT_BD_ooc.xdc
