/** 
* _Architecture is a Java class represention of one of the components
* of the Reference Architecture of TOP_LEVEL.
* <p>
* It extends from the class Component like all other elements of TOP_LEVEL because
* this model follows the Composite design patter and SCA (Service Component Architecture)
* <p>
* It also implements the following services:
* <ul>
* <li>_i_ISA</li>,
* <li>_i_MemSizes</li>,
* <li>_i_Registers</li>
* </ul>
* <p>
* In addendum, this class also encapsulates all the configurable properties of the 
* component it represent, as well as all the accessor methods to change its values
*
* <b>NOTE:</b> Code autmatically generated by Elaboration Language
*
* @author ESRG (Embedded Systems Research Group) class of 2015/2016
* @version 1.0 
* @since 02/05/2016
*/

package EL.Components;

import java.util.ArrayList;
import java.util.Arrays;
import EL.ElaborationError;

public class _Architecture extends Component implements _i_ISA, _i_MemSizes, _i_Registers
{
	//-------------------------- NO SUBCOMPONENTS -------------------------//
	
	
	//--------------------------- NO REFERENCES ---------------------------//

	
	//----------------------------- PROPERTIES ----------------------------//
	private String _name;

	public _Architecture()
	{
		//There are no subcomponents to be initialized.
		
		
		//There are bindings to be done.
	}
	//---------------------------------------------------------------------//
	//-------------------- PROPERTIES ACCESSOR METHODS --------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for _name
	*
	* @return _name (Property in _Architecture)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/			
	public String get_name()
	{
		return this._name;
	}						
		
	/**
	* Setter method for _name taking the restriction associated to _name 
	* into account.
	*
	* @param _arg (Value to set _name in _Architecture)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_name(String _arg)
	{
		this._name = _arg;
	}
	
	/**
	* Setter method for _name with no restrictions and no parameters.
	* Asserting the value of _name to its default value.
	*
	* @param null 
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_name()
	{
		ElaborationError.elaborationError("No value to be assigned to _name.");
	}
	//---------------------------------------------------------------------//
	//----------------- END OF PROPERTIES ACCESSOR METHODS ----------------//
	//---------------------------------------------------------------------//
	
	//---------------------------------------------------------------------//
	//--------------------- SERVICES ACCESSOR METHODS ---------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for the component that implements _i_ISA
	*
	* @return this (Component _Architecture)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_ISA()
	{
		return this;
	}
	/**
	* Getter method for the component that implements _i_MemSizes
	*
	* @return this (Component _Architecture)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_MemSizes()
	{
		return this;
	}
	/**
	* Getter method for the component that implements _i_Registers
	*
	* @return this (Component _Architecture)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_Registers()
	{
		return this;
	}
	
	//---------------------------------------------------------------------//
	//------------------ END OF SERVICES ACCESSOR METHODS -----------------//
	//---------------------------------------------------------------------//
}	
