/** 
* _DBT is a Java class represention of one of the components
* of the Reference Architecture of TOP_LEVEL.
* <p>
* It extends from the class Component like all other elements of TOP_LEVEL because
* this model follows the Composite design patter and SCA (Service Component Architecture)
* <p>
* This class contains objects(subcomponents) of the following types:
* <ul>
* <li>_SourceCluster</li>	
* <li>_TargetCluster</li>	
* <li>_CodeCache</li>	
* <li>_TranslationCache</li>	
* <li>_DBTEngine</li>	
* </ul>
* <p>
* In addendum, this class also encapsulates all the configurable properties of the 
* component it represent, as well as all the accessor methods to change its values
*
* <b>NOTE:</b> Code autmatically generated by Elaboration Language
*
* @author ESRG (Embedded Systems Research Group) class of 2015/2016
* @version 1.0 
* @since 02/05/2016
*/

package EL.Components;

import java.util.ArrayList;
import java.util.Arrays;
import EL.ElaborationError;

public class _DBT extends Component 
{
	//--------------------------- SUBCOMPONENTS ---------------------------//
	protected _SourceCluster _srcCluster;
	protected _TargetCluster _trgCluster;
	protected _CodeCache _cCache;
	protected _TranslationCache _tCache;
	protected _DBTEngine _dbtEngine;
	
	//----------------------------- REFERENCES ----------------------------//
	protected _i_RunDBT _r_RunDBT;
	protected _i_Init _r_Init;
	
	//--------------------------- NO PROPERTIES ---------------------------//


	public _DBT()
	{
		//Initialization of subcomponents.
		_srcCluster = new _SourceCluster();
		_trgCluster = new _TargetCluster();
		_cCache = new _CodeCache();
		_tCache = new _TranslationCache();
		_dbtEngine = new _DBTEngine();
		
		//Binding references to services.
		_cCache.set_r_ISA((_i_ISA)_srcCluster.get_i_ISA());
		_trgCluster.set_pr_SrcRegisters((_i_Registers)_srcCluster.get_i_Registers());
		_trgCluster.set_pr_PCAccessors((_i_PCAccessors)_srcCluster.get_i_PCAccessors());
		_dbtEngine.set_pr_DMem((_i_DMem)_srcCluster.get_i_DMem());
		_dbtEngine.set_pr_Decode((_i_Decode)_srcCluster.get_i_Decode());
		_tCache.set_r_ISA((_i_ISA)_trgCluster.get_i_ISA());
		_srcCluster.set_pr_Generate((_i_Generate)_trgCluster.get_i_Generate());
		_trgCluster.set_pr_TCache((_i_TCache)_tCache.get_i_TCache());
		_srcCluster.set_pr_CCache((_i_CCache)_cCache.get_i_CCache());
		this.set_r_RunDBT((_i_RunDBT)_dbtEngine.get_i_RunDBT());
		_dbtEngine.set_pr_TransTCache((_i_TCache)_tCache.get_i_TCache());
		this.set_r_Init((_i_Init)_dbtEngine.get_i_Init());
	}
	//---------------------------------------------------------------------//
	//------------------- SUBCOMPONENTS ACCESSOR METHODS ------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for the subcomponent _SourceCluster of _DBT
	*
	* @return _SourceCluster
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _SourceCluster get_srcCluster()
	{
		return this._srcCluster;
	}
	/**
	* Getter method for the subcomponent _TargetCluster of _DBT
	*
	* @return _TargetCluster
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _TargetCluster get_trgCluster()
	{
		return this._trgCluster;
	}
	/**
	* Getter method for the subcomponent _CodeCache of _DBT
	*
	* @return _CodeCache
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _CodeCache get_cCache()
	{
		return this._cCache;
	}
	/**
	* Getter method for the subcomponent _TranslationCache of _DBT
	*
	* @return _TranslationCache
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _TranslationCache get_tCache()
	{
		return this._tCache;
	}
	/**
	* Getter method for the subcomponent _DBTEngine of _DBT
	*
	* @return _DBTEngine
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _DBTEngine get_dbtEngine()
	{
		return this._dbtEngine;
	}
	//---------------------------------------------------------------------//
	//--------------- END OF SUBCOMPONENTS ACCESSOR METHODS ---------------//
	//---------------------------------------------------------------------//
	
	//---------------------------------------------------------------------//
	//--------------------- REFERENCES ACCESSOR METHODS -------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for _r_RunDBT which type is _i_RunDBT
	*
	* @return _r_RunDBT (Reference in _DBT)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_RunDBT get_r_RunDBT()
	{
		return this._r_RunDBT;
	}
	/**
	* Setter method for _r_RunDBT which type is _i_RunDBT
	*
	* @param _arg (Component to set r_RunDBT in _DBT that implements _i_RunDBT)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_r_RunDBT(_i_RunDBT _arg)
	{
		this._r_RunDBT = _arg;
	}			
	/**
	* Getter method for _r_Init which type is _i_Init
	*
	* @return _r_Init (Reference in _DBT)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_Init get_r_Init()
	{
		return this._r_Init;
	}
	/**
	* Setter method for _r_Init which type is _i_Init
	*
	* @param _arg (Component to set r_Init in _DBT that implements _i_Init)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_r_Init(_i_Init _arg)
	{
		this._r_Init = _arg;
	}			
	//---------------------------------------------------------------------//
	//----------------- END OF REFERENCES ACCESSOR METHODS ----------------//	
	//---------------------------------------------------------------------//	
	
}	
