/** 
* _SourceEnv is a Java class represention of one of the components
* of the Reference Architecture of TOP_LEVEL.
* <p>
* It extends from the class Component like all other elements of TOP_LEVEL because
* this model follows the Composite design patter and SCA (Service Component Architecture)
* <p>
* This class contains objects(subcomponents) of the following types:
* <ul>
* <li>_DataMemory</li>	
* </ul>
* <p>
* It also implements the following services:
* <ul>
* <li>_i_PCAccessors</li>
* </ul>
* <p>
* In addendum, this class also encapsulates all the configurable properties of the 
* component it represent, as well as all the accessor methods to change its values
*
* <b>NOTE:</b> Code autmatically generated by Elaboration Language
*
* @author ESRG (Embedded Systems Research Group) class of 2015/2016
* @version 1.0 
* @since 02/05/2016
*/

package EL.Components;

import java.util.ArrayList;
import java.util.Arrays;
import EL.ElaborationError;

public class _SourceEnv extends Component implements _i_PCAccessors
{
	//--------------------------- SUBCOMPONENTS ---------------------------//
	protected _DataMemory _dataMem;
	
	//--------------------------- NO REFERENCES ---------------------------//

	
	//--------------------------- NO PROPERTIES ---------------------------//


	public _SourceEnv()
	{
		//Initialization of subcomponents.
		_dataMem = new _DataMemory();
		
		//There are bindings to be done.
	}
	//---------------------------------------------------------------------//
	//------------------- SUBCOMPONENTS ACCESSOR METHODS ------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for the subcomponent _DataMemory of _SourceEnv
	*
	* @return _DataMemory
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _DataMemory get_dataMem()
	{
		return this._dataMem;
	}
	//---------------------------------------------------------------------//
	//--------------- END OF SUBCOMPONENTS ACCESSOR METHODS ---------------//
	//---------------------------------------------------------------------//
	
	//---------------------------------------------------------------------//
	//--------------------- REFERENCES ACCESSOR METHODS -------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for _pr_MemSizes which type is _i_MemSizes
	* <p>
	* This reference is promoted from _dataMem
	*
	* @return _r_MemSizes (Reference in _dataMem)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public _i_MemSizes get_pr_MemSizes()
	{
		return _dataMem.get_r_MemSizes();
	}
	/**
	* Setter method for _pr_MemSizes which type is _i_MemSizes
	* <p>
	* This reference is promoted from _dataMem
	*
	* @param _arg (Component to set _r_MemSizes in _dataMem that implements _i_MemSizes)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	protected void set_pr_MemSizes(_i_MemSizes _arg)
	{
		_dataMem.set_r_MemSizes(_arg);
	}			
	//---------------------------------------------------------------------//
	//----------------- END OF REFERENCES ACCESSOR METHODS ----------------//	
	//---------------------------------------------------------------------//	
	
	//---------------------------------------------------------------------//
	//--------------------- SERVICES ACCESSOR METHODS ---------------------//
	//---------------------------------------------------------------------//
	/**
	* Getter method for the component that implements _i_PCAccessors
	*
	* @return this (Component _SourceEnv)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_PCAccessors()
	{
		return this;
	}
	
	/**
	* Getter method for the component that implements _i_DMem
	* <p>
	* This service is promoted from _dataMem
	*
	* @return Component (_dataMem or any subcomponent)
	*
	* <b>NOTE:</b> Code autmatically generated by Elaboration Language
	*/
	public Component get_i_DMem()
	{
		return _dataMem.get_i_DMem();
	}
	//---------------------------------------------------------------------//
	//------------------ END OF SERVICES ACCESSOR METHODS -----------------//
	//---------------------------------------------------------------------//
}	
